### ISSUE TITLE
Format JSON invalide

### ISSUE THREAD

**Issue by Bebel00** [EduWireApps/ecoledirecte-api-docs#1]
Bonsoir
Avec ce simple programme
 ```
import requests

login = {"utilisateur": "test", "motdepasse": "TEST"}
r = requests.post("https://api.ecoledirecte.com/v3/login.awp", data=login)
print(r.json())
```

J'ai l'erreur suivante:
`
 {'code': 40129, 'token': '', 'message': 'Format JSON invalide', 'data': {'accounts': []}}`

**Comment by MaitreRouge** [comment]
La solution a été donnée sur [le serveur discord](https://discord.gg/V5GMMGJ9ep), le second argument de la méthode post aurait du être `f"data={login}"`,
Quand on dit que tout doit être envoyé sous la forme de plain text, c'est vraiment tout ;)
