### ISSUE TITLE
Retour d'erreur 

### ISSUE THREAD

**Issue by silversmarty** [EduWireApps/ecoledirecte-api-docs#10]
Bonjour à tous,

après quelques essais, l'API me retourne un message "spam", indiquant que j'ai été ciblé comme un utilisateur abusif : 

`Nous avons enregistré votre adresse IP ainsi que l'ensemble des informations relatives à vos requêtes pour analyser votre activité`

Je précise que je n'ai fait que des tests "manuels" (pas de cron pour faire une requête toutes les dix secondes), donc selon moi pas vraiment abusif ... 
Est-ce que l'un d'entre vous a eu ce message également ? Est-ce que les conditions pour tomber dans le groupe des spammeurs sont connues ? Comment en sortir ? J'ai attendu 48h avant de lancer la requête suivante, et j'obtiens toujours ce message ...

Merci !

**Comment by madsenfr** [comment]
Salut,
J'ai jamais eu ce message venant de l'API, mais ma gamine a eu un message sur École Directe, pour lui demander si elle était à l'origine des appels récurrent (en phase de tests), elle à confirmé car elle savait que je bossais dessus, du coup l'API a continué de fonctionner.
Donc je dirais d'aller voir sur l'appli École Directe si y'a pas une notif ou un mail à valider quelque part.

**Comment by azgaresncf** [comment]
> Bonjour à tous,
> 
> après quelques essais, l'API me retourne un message "spam", indiquant que j'ai été ciblé comme un utilisateur abusif :
> 
> `Nous avons enregistré votre adresse IP ainsi que l'ensemble des informations relatives à vos requêtes pour analyser votre activité`
> 
> Je précise que je n'ai fait que des tests "manuels" (pas de cron pour faire une requête toutes les dix secondes), donc selon moi pas vraiment abusif ... Est-ce que l'un d'entre vous a eu ce message également ? Est-ce que les conditions pour tomber dans le groupe des spammeurs sont connues ? Comment en sortir ? J'ai attendu 48h avant de lancer la requête suivante, et j'obtiens toujours ce message ...
> 
> Merci !

Il y a probablement des "parades", notamment (théorie) avec la version de l'API d'EcoleDirecte, mise dans la page de connexion en blanc.
![image](https://github.com/EduWireApps/ecoledirecte-api-docs/assets/50982832/f2b5702f-b771-4f62-9550-69ca92281588)

**Comment by silversmarty** [comment]
Merci pour vos bonnes idées !

- J'ai rajouté un "&v=4.40.0" dans l'url (comme dans les appels depuis la page du site) mais sans succès
- Aucun message me demandant de confirmer quoi que ce soit sur le site Ecole Directe

Du coup je sèche un peu ... peut-être faudrait-il que je réessaye depuis une autre IP, mais derrière ma box c'est compliqué :-P

**Comment by azgaresncf** [comment]
> Merci pour vos bonnes idées !
> 
>     * J'ai rajouté un "&v=4.40.0" dans l'url (comme dans les appels depuis la page du site) mais sans succès
> 
>     * Aucun message me demandant de confirmer quoi que ce soit sur le site Ecole Directe
> 
> 
> Du coup je sèche un peu ... peut-être faudrait-il que je réessaye depuis une autre IP, mais derrière ma box c'est compliqué :-P

Avez-vous des mails vous indiquant une connexion suspecte à votre compte EcoleDirecte ?

**Comment by azgaresncf** [comment]
![image](https://github.com/EduWireApps/ecoledirecte-api-docs/assets/50982832/23965309-c447-449c-b5e6-ec86346fb5f3)
Il doit réellement y avoir un coup de butoir fait par EcoleDirecte concernant leurs requêtes... on dirait presque qu'elles doivent correspondre aux leurs au millimètre près, sinon on meurt...

**Comment by azgaresncf** [comment]
voici l'exemple d'une requête qui devrait "bien se passer":
```js
await fetch("https://api.ecoledirecte.com/v3/login.awp?v=4.40.0", {
    "credentials": "omit",
    "headers": {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0",
        "Accept": "application/json, text/plain, */*",
        "Accept-Language": "fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3",
        "Content-Type": "application/x-www-form-urlencoded",
        "Sec-Fetch-Dest": "empty",
        "Sec-Fetch-Mode": "cors",
        "Sec-Fetch-Site": "same-site"
    },
    "referrer": "https://www.ecoledirecte.com/",
    "body": "data={\n    \"identifiant\": \"identifiant\",\n    \"motdepasse\": \"mdp\",\n    \"isReLogin\": false,\n    \"uuid\": \"\"\n}",
    "method": "POST",
    "mode": "cors"
});``

**Comment by Odissine** [comment]
Pour ma part pas de mail, j'ai toujours une erreur 403 quand je tente d'appeler juste le cahier de texte ou l'emploi du temps ...
Mon erreur 403 vient du fait que j'ai deux enfants , et que l'API marche du coup avec deux comptes il faut bien utiliser le compte A pour l'élève A et le compte B avec l'elève B je pensais qu'un simple compte suffirait car je récupère bien dans data les infos ...

**Comment by azgaresncf** [comment]
> Pas de mail ou de communication quelle qu'elle soit (même pas dans mes spams).
> Ce qui est étrange, c'est que ma première requête (login) passe correctement, mais que la seconde (que j'ai temporisée 5 secondes plus tard, pour ne pas trop solliciter l'API) renvoie cette erreur. 
> 
> Ca m'intéresse de savoir comment vous avez construit vos requêtes : Je suis sous Node Red, est-ce que l'un d'entre nous l'a fait avec Node Red ? Si oui, peut-il partager ses noeuds ?

Plutôt étrange que aucun mail n'est envoyé. Néanmoins, essayez de garder votre token dans une variable.

Elle représente un temps de connexion défini selon l'activité de votre compte.

**Comment by azgaresncf** [comment]
> Pour ma part pas de mail, j'ai toujours une erreur 403 quand je tente d'appeler juste le cahier de texte ou l'emploi du temps ...
> Mon erreur 403 vient du fait que j'ai deux enfants , et que l'API marche du coup avec deux comptes il faut bien utiliser le compte A pour l'élève A et le compte B avec l'elève B je pensais qu'un simple compte suffirait car je récupère bien dans data les infos ... 

Il me semble qu'il y a un endpoint qui permet de changer de compte. Je vais essayer d'investiguer ça en tout cas.

**Comment by silversmarty** [comment]
J'ai trouvé ! 
C'est évidemment un truc idiot : j'utilisais l'id du parent, plutôt que l'id de l'élève pour faire la requête ! Avec l'id de l'élève, ça fonctionne parfaitement !

**Comment by azgaresncf** [comment]
> J'ai trouvé ! 
> C'est évidemment un truc idiot : j'utilisais l'id du parent, plutôt que l'id de l'élève pour faire la requête ! Avec l'id de l'élève, ça fonctionne parfaitement !

> Oh parfait !
> Ce n'est pas grave au passage, on fait tous des erreurs 😉
