### ISSUE TITLE
Mot de passe invalide

### ISSUE THREAD

**Issue by madsenfr** [EduWireApps/ecoledirecte-api-docs#11]
Salut,
Est-ce que quelqu'un aurait une idée de pourquoi l'appel à "login" fonctionne bien depuis Postman mais retourne "Mot de passe invalide !" depuis une instance NodeJs en ligne sur https://runkit.com/ ?
Pour info, une fois que j'ai un token, les autres appels (ex. emploi du temps) fonctionnent bien.
J'ai une skill Alexa (app pour l'enceinte connectée Amazon) qui à commencé à déconner en fin d'année scolaire de l'année dernière.
Alexa embarque aussi son NodeJS et j'ai le même problème de mot de passe invalide, qui est plus facile à reproduire et à partager sur via Runkit.

**Comment by azgaresncf** [comment]
> Salut, Est-ce que quelqu'un aurait une idée de pourquoi l'appel à "login" fonctionne bien depuis Postman mais retourne "Mot de passe invalide !" depuis une instance NodeJs en ligne sur https://runkit.com/ ? Pour info, une fois que j'ai un token, les autres appels (ex. emploi du temps) fonctionnent bien. J'ai une skill Alexa (app pour l'enceinte connectée Amazon) qui à commencé à déconner en fin d'année scolaire de l'année dernière. Alexa embarque aussi son NodeJS et j'ai le même problème de mot de passe invalide, qui est plus facile à reproduire et à partager sur via Runkit.

Ils surveillent et filtrent les requêtes, pour éviter que des personnes malintentionnés ou des bots se connectent à des comptes.

**Comment by azgaresncf** [comment]
Par défaut, lorsque quelqu'un d'un autre pays vient à se connecter sur un compte EcoleDirecte, ils (EcoleDirecte) font croire que le mot de passe est invalide, alors qu'il envoie un mail au propriétaire du compte lui demandant si il a bien été à l'origine de la connexion.

**Comment by azgaresncf** [comment]
> Ça veut dire qu'on ne pourrait pas utiliser le site officiel à l'étranger ?

À moins que tu approuves chaque connexion faite sur le compte (si il ne s'agit pas d'une IP fixe), il n'est pas possible de pouvoir l'utiliser.

Il faudrait créer un système permettant de récupérer le mail et de l'approuver à ta place.
