### ISSUE TITLE
Missing Parameters

### ISSUE THREAD

**Issue by Odissine** [EduWireApps/ecoledirecte-api-docs#12]
Hello, je sais pas si c'est un bug ou une évolution de comment appeler l'API ... mais j'arrive pas à appeler le cahier de texte

POST > https://api.ecoledirecte.com/v3/E/{{eleve_id}}/cahierdetexte.awp?verbe=get
POST > https://api.ecoledirecte.com/v3/eleves/{{eleve_id}}/cahierdetexte.awp?verbe=get
GET > https://api.ecoledirecte.com/v3/E/{{eleve_id}}/cahierdetexte.awp
GET > https://api.ecoledirecte.com/v3/eleves/{{eleve_id}}/cahierdetexte.awp

J'ai testé de rajouter au cas ou dans body
{ "date" : "2023-10-03" }

Tout est ok mais j'ai sans arrêt le meme résultat : 

{"code":225, "token":"", "host":"HTTPxxx", "message":"Paramètres spécifiés incorrects !"}

Si vous avez une idée d'ou vient le problème ? J'arrive à bien récupérer l'emploi du temps (POST + verbe=get) mais le cahier de texte ca veut pas :(

**Comment by azgaresncf** [comment]
![image](https://github.com/EduWireApps/ecoledirecte-api-docs/assets/50982832/2779a1c1-d782-4345-b193-e65cb0654887)
La requête selon la date est disponible ici

**Comment by MaitreRouge** [comment]
Une update @Odissine ?

**Comment by silversmarty** [comment]
Idem chez moi, je n'arrive pas à utiliser le cahier de texte (même retour en erreur)

**Comment by Odissine** [comment]
> Une update @Odissine ?

Pas pour l'instant jai pas eu le temps de m'y repencher et je vois que je suis pas le seul, je creuse ça rapidement dès que jai le temps :)

**Comment by MaitreRouge** [comment]
Cette issue n'a plus d'activité depuis un petit moment, on la considère donc comme résolue !

**Comment by silversmarty** [comment]
Hum ... il n'y a pas eu de solution apportée, il me semble ? Je viens de refaire le test, et c'est toujours KO :-(

**Comment by silversmarty** [comment]
Merci @MaitreRouge pour la réouverture ! Comment est-ce que je peux aider à la résolution de ce bug ?

**Comment by amolinarius** [comment]
Bonjour à tous,
Personnellement le cahier de textes marche pour moi.
J'ai remarqué qu'EcoleDirecte renvoie une `erreur 225` également lorsqu'il n'y a simplement pas le token ou pas de User-Agent.
Avez-vous pensé à mettre les deux dans les headers de la requête ?
![image](https://github.com/EduWireApps/ecoledirecte-api-docs/assets/89464182/44a53d8a-cd8c-47eb-a521-73b52c3a42d2)

**Comment by silversmarty** [comment]
Hello @amolinarius !
Merci pour message, j'ai bien vérifié de mon côté et j'ai bien le token et le user agent. J'ai repris la même config que d'autres appels API d'école directe (comme l'emploi du temps), ça me permet de dire que le problème ne vient pas de là. Mais le fait que cela marche chez toi est encourageant !

Est-ce que tu pourrais partager la config de ton appel API ? Si tu es sur Node Red, c'est un json il me semble, ça nous permettrait d'y voir plus clair ;-)

Merci !

**Comment by amolinarius** [comment]
Bonsoir @silversmarty !
Mon appel est fait avec une fonction JavaScript, la voici :
```js
function sendXHR(url, queryString, body, callback) {
    var xhr = new XMLHttpRequest();
    xhr.onloadend = r=>callback(r.target);
    xhr.open('POST', `https://api.ecoledirecte.com/v3/${url}.awp${queryString.length>0?'?':''}${queryString.join('&')}`);
    xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
    if (token) {xhr.setRequestHeader('X-Token', token)}
    xhr.send(encodeURIComponent('data='+body));
}
```
et je l'appelle avec :
```js
sendXHR(
    `/Eleves/${id}/cahierdetexte`, // url
    ['verbe=get'],  // paramètres dans l'url
    '{}', // body
    callback // une fonction prenant la réponse à la requête comme paramètre 
);
```

**Note : ** Comme j'ai utilisé cette fonction dans un script de navigateur, je n'ai pas mis de User-Agent, pour ceux qui testeraient avec NodeJS

**Comment by silversmarty** [comment]
Merci @amolinarius , j'ai trouvé le problème !
J'ai rajouté le "data={}" dans le body, que j'avais oublié ! J'ai aussi enlevé le paramètre v=4.40.0, et rajouté le header Content-Type !

Thanks again !

**Comment by amolinarius** [comment]
De rien !
Je voulais juste préciser que le paramètre `v=4.40.0` n'est pas obligatoire mais on peut quand même le mettre.
J'imagine qu'il sert à utiliser une version précise de l'API ou dans l'autre cas simplement la dernière version.
