### ISSUE TITLE
Websocket ?

### ISSUE THREAD

**Issue by 8borane8** [EduWireApps/ecoledirecte-api-docs#13]
Salut il y a un socketToken donc il y a un websocket ? Si oui pourrais tu l'ajouter à la doc j'en aurais besoin merci beaucoup.

**Comment by azgaresncf** [comment]
> Salut il y a un socketToken donc il y a un websocket ? Si oui pourrais tu l'ajouter à la doc j'en aurais besoin merci beaucoup.

Bonjour.
Oui, il existe probablement un serveur websocket, mais je laisse aller te renseigner 😉

**Comment by MaitreRouge** [comment]
Cette issue n'a plus d'activité depuis un petit moment, on la considère donc comme résolue !
