### ISSUE TITLE
Carnet de correspondance : Erreur 403

### ISSUE THREAD

**Issue by MrBeam89** [EduWireApps/ecoledirecte-api-docs#15]
Bonjour, il y a un problème en ce qui concerne le carnet de correspondance, voici la réponse que j'ai obtenu :

{
    "code": 403,
    "token": "token-secret-ici-1234",
    "host": "HTTP68",
    "message": " - Nous avons enregistr\u00e9 votre adresse IP ainsi que l'ensemble des informations relatives \u00e0 vos requ\u00eates pour analyser votre activit\u00e9"
}

Je n'utilise pas de VPN, et je ne me suis pas amusé à spammer les requêtes. Savez-vous pourquoi EcoleDirecte refuse spécifiquement le carnet de correspondance et rien d'autre ? Merci d'avance

**Comment by MaitreRouge** [comment]
Hey,

La réponse à déjà été donné dans une issue précédente; Je vais donc te rediriger vers cette dernière et hésite pas à revenir vers nous !

Issue en question : #10 (https://github.com/EduWireApps/ecoledirecte-api-docs/issues/10)
