### ISSUE TITLE
Suggestion : Interface Alternative

### ISSUE THREAD

**Issue by Equalis-programming** [EduWireApps/ecoledirecte-api-docs#22]
Salut
Je suis un petit développeur autodidacte, se spécialisant en Applications C# (même si j'ai un peu contribué à ce projet).
J'ai vu et ai été séduit par votre logiciel YNotes et je présentais ici mon aide : maintenir un projet n'est pas simple, je le sais... C'est pour ça que j'aimerais vous aider à faire revivre YNotes pour, peut-être, reprendre les mises-à-jour, ajouter de la compatibilité avec d'autres interfaces...

Vous pouvez trouver mes contacts ici pour qu'on en discute : [Dynwares - About](https://dynwares.com/about)

**Comment by MaitreRouge** [comment]
Hey, mauvais repo, si tu veux discuter sur le serveur discord sur lequel le projet a vu le jour le voici : https://discord.gg/7RQAyUtMVw
Ici ce n'est qu'une documentation pour ED
