### ISSUE TITLE
Problème d'accès au cloud EcoleDirecte

### ISSUE THREAD

**Issue by LouisSimon2020** [EduWireApps/ecoledirecte-api-docs#23]
Bonjour,
Est ce que quelqu'un pourrait m'aider à accéder au cloud EcoleDirecte via l'API car je n'y arrive pas,
 Merci d'avance,
L-Simon

**Comment by MaitreRouge** [comment]
Bonjour Simon,
Pour qu'on puisse t'aider il faudrait que tu nous donnes plus d'informations sur le problèmes que tu rencontres.
Marc

**Comment by LouisSimon2020** [comment]
Bien sûr, voici mon code pour accéder au système de téléchargement du cloud
EcoleDirecte:
curl -v \ -X POST \ -H "X-Token: f7cfdee0-27e5-49bb-b9c1-a2d79ea713a0" \ -H
"Content-Type: application/x-www-form-urlencoded" \ -H "User-Agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/109.0.0.0 Safari/537.36" \ -d "data={ forceDownload: 0 }" \ "
https://api.ecoledirecte.com/v3/telechargement.awp?verbe=post&mode=destinataire&leTypeDeFichier=CLOUD&fichierId=%5C%5C0601145U%5C%5CE%5C%5C1714%5C%5CEMC%5C%5CFrise
"

**Comment by LouisSimon2020** [comment]
Et voici ce que ça me retourne
Oups une erreur est survenue ...: 522

**Comment by MaitreRouge** [comment]
Désolé du délai, j'ai été un peu occupé dernièrement...
De ce que je vois, ton XToken me parait un peu court, de mémoire il était beaucoup plus long et ne ressemblait à tout sauf un uuid. Est ce que tu es sur que ton XToken est correct ?

**Comment by LouisSimon2020** [comment]
Ne t’inquiètes pas ce n’est pas grave, oui je suis sûr que mon x-token est
correct,c’est juste que sur l’application on ne voit pas la fin, je pense
que le problème proviendrait plutôt des paramètres.

**Comment by MaitreRouge** [comment]
Est-ce que tu peux lister les documents ?

**Comment by LouisSimon2020** [comment]
Voilà: {  "code": 200,  "token": "e6db9efa-ad5c-4fbb-9758-e9752b369515",  "host": "HTTP71",  "data": [    {      "type": "folder",      "libelle": "/",      "date": "2024-02-08 19:35:00",      "taille": 18581256,      "quota": 2147483648,      "id": "\\0601145U\\E\\1714",      "isLoaded": true,      "readonly": false,      "children": [        {          "type": "folder",          "libelle": "EMC",          "date": "2023-12-05 20:59:00",          "taille": 6474952,          "id": "\\0601145U\\E\\1714\\EMC",          "isLoaded": true,          "readonly": false,          "children": [            {              "type": "folder",              "libelle": "Frise",              "date": "2023-12-05 20:57:00",              "taille": 2081998,              "id": "\\0601145U\\E\\1714\\EMC\\Frise",              "isLoaded": false,              "readonly": false,              "children": []            },            {              "type": "folder",              "libelle": "SchÃ©mas",              "date": "2023-12-05 20:59:00",              "taille": 4392954,              "id": "\\0601145U\\E\\1714\\EMC\\SchÃ©mas",              "isLoaded": false,              "readonly": false,              "children": []            }          ]        },        {          "type": "folder",          "libelle": "Maths",          "date": "2023-12-05 20:57:00",          "taille": 11299848,          "id": "\\0601145U\\E\\1714\\Maths",          "isLoaded": true,          "readonly": false,          "children": [            {              "type": "file",              "libelle": "1e`re de couverture maths (jpeg).jpg",              "date": "2023-12-03 20:56:00",              "taille": 652558,              "id": "\\\\CLOUD20\\cloud\\0601145U\\E\\1714\\Maths\\1e`re de couverture maths (jpeg).jpg",              "readonly": false,              "proprietaire": {"id": 1714, "type": "E", "nom": "XXX", "prenom": "XXX", "particule": ""}            },            {              "type": "file",              "libelle": "1e`re de couverture maths.pdf",              "date": "2023-12-03 20:56:00",              "taille": 680050,              "id": "\\\\CLOUD20\\cloud\\0601145U\\E\\1714\\Maths\\1e`re de couverture maths.pdf",              "readonly": false,              "proprietaire": {"id": 1714, "type": "E", "nom": "XXX", "prenom": "XXX", "particule": ""}            },            {              "type": "file",              "libelle": "4e`me de couverture maths.pdf",              "date": "2023-12-03 20:56:00",              "taille": 5101771,              "id": "\\\\CLOUD20\\cloud\\0601145U\\E\\1714\\Maths\\4e`me de couverture maths.pdf",              "readonly": false,              "proprietaire": {"id": 1714, "type": "E", "nom": "XXX", "prenom": "XXX", "particule": ""}            },            {              "type": "file",              "libelle": "4e`me de couverture Maths (jpeg).jpg",              "date": "2023-12-03 20:56:00",              "taille": 4865469,              "id": "\\\\CLOUD20\\cloud\\0601145U\\E\\1714\\Maths\\4e`me de couverture Maths (jpeg).jpg",              "readonly": false,              "proprietaire": {"id": 1714, "type": "E", "nom": "XXX", "prenom": "XXX", "particule": ""}            }          ]        },        {          "type": "folder",          "libelle": "projet latin",          "date": "2024-01-29 16:10:00",          "taille": 714869,          "id": "\\0601145U\\E\\1714\\projet latin",          "isLoaded": true,          "readonly": false,          "children": [            {              "type": "file",              "libelle": "1311427-Le_Discobole.jpg",              "date": "2024-01-15 16:05:00",              "taille": 32121,              "id": "\\\\CLOUD20\\cloud\\0601145U\\E\\1714\\projet latin\\1311427-Le_Discobole.jpg",              "readonly": false,              "proprietaire": {"id": 1714, "type": "E", "nom": "XXX", "prenom": "XXX", "particule": ""}            },            {              "type": "file",              "libelle": "23689.jpg",              "date": "2024-01-15 16:05:00",              "taille": 53686,              "id": "\\\\CLOUD20\\cloud\\0601145U\\E\\1714\\projet latin\\23689.jpg",              "readonly": false,              "proprietaire": {"id": 1714, "type": "E", "nom": "XXX", "prenom": "XXX", "particule": ""}            },            {              "type": "file",              "libelle": "carte athenes.jpeg",              "date": "2024-01-29 16:02:00",              "taille": 52118,              "id": "\\\\CLOUD20\\cloud\\0601145U\\E\\1714\\projet latin\\carte athenes.jpeg",              "readonly": false,              "proprietaire": {"id": 1714, "type": "E", "nom": "XXX", "prenom": "XXX", "particule": ""}            },            {              "type": "file",              "libelle": "istockphoto-166667813-612x612.jpgEnvoyé de mon iPadLe 17 févr. 2024 à 4:34 PM, Marc M ***@***.***> a écrit :﻿
Est-ce que tu peux lister les documents ?

**Comment by MaitreRouge** [comment]
Je viens de réussir de télécharger un document, voici exactement ce que j'ai mis dans ma requête. Je te laisse comparer avec la tienne pour voir ce qui te manque. J'ai essayé de faire la requette la plus courte. Je te conseille de visionner ma réponse via GitHub pour pas avoir de pb de mise en forme !

URL :
```
https://api.ecoledirecte.com/v3/telechargement.awp
?verbe=get
&v=4.51.1
&leTypeDeFichier=CLOUD
&fichierId=%5C%5C0441928G%5C%5CE%5C%5C1913
&idEntity=1913
&typeEntity=E 
```

Header : 
![image](https://github.com/EduWireApps/ecoledirecte-api-docs/assets/39885214/883f6800-fb3e-479b-8de2-0e0bd02ed6b6)

Payload :
![image](https://github.com/EduWireApps/ecoledirecte-api-docs/assets/39885214/cf9c5e35-1a2f-400d-8aa7-54528f8b156d)

Ma requete sous cURL :
```
curl --request POST \
  --url 'https://api.ecoledirecte.com/v3/telechargement.awp?verbe=get&v=4.51.1&leTypeDeFichier=CLOUD&fichierId=%5C%5C0441928G%5C%5CE%5C%5C1913&idEntity=1913&typeEntity=E' \
  --header 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36' \
  --header 'x-token: XXXXXXXXXXXXX' \
  --data 'data: {
    "forceDownload": 0,
    "idEntity": 1913,
    "typeEntity": "E"
}'
```

**Comment by MaitreRouge** [comment]
Pour mieux que tu voies ce qui compose l'url voici un screenshot avec tous les arguments : 
URL de base : https://api.ecoledirecte.com/v3/telechargement.awp
![image](https://github.com/EduWireApps/ecoledirecte-api-docs/assets/39885214/7cf7698f-d946-4a6b-a04e-2bce4eae7542)

**Comment by LouisSimon2020** [comment]
Merci beaucoup pour ton aide je vais tester.Envoyé de mon iPadLe 17 févr. 2024 à 4:47 PM, Marc M ***@***.***> a écrit :﻿
Je viens de réussir de télécharger un document, voici exactement ce que j'ai mis dans ma requête. Je te laisse comparer avec la tienne pour voir ce qui te manque. J'ai essayé de faire la requette la plus courte. Je te conseille de visionner ma réponse via GitHub pour pas avoir de pb de mise en forme !
URL :
https://api.ecoledirecte.com/v3/telechargement.awp
?verbe=get
&v=4.51.1
&leTypeDeFichier=CLOUD
&fichierId=%5C%5C0441928G%5C%5CE%5C%5C1913
&idEntity=1913
&typeEntity=E 

Header :
image.png (view on web)
Payload :
image.png (view on web)
Ma requete sous cURL :
curl --request POST \
  --url 'https://api.ecoledirecte.com/v3/telechargement.awp?verbe=get&v=4.51.1&leTypeDeFichier=CLOUD&fichierId=%5C%5C0441928G%5C%5CE%5C%5C1913&idEntity=1913&typeEntity=E' \
  --header 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36' \
  --header 'x-token: XXXXXXXXXXXXX' \
  --data 'data: {
    "forceDownload": 0,
    "idEntity": 1913,
    "typeEntity": "E"
}'

**Comment by LouisSimon2020** [comment]
Salut Marc, cela ne fonctionne pas ou presque, lorsque je met le chemin d'un fichier spécifique ca me dit que le fichier n'existe pas et lorsque je met le chemin d'un dossier ca me revoient des milliers de lignes dans un format étrange.
<img width="1857" alt="Capture d’écran 2024-02-18 à 17 41 43" src="https://github.com/EduWireApps/ecoledirecte-api-docs/assets/61110029/10191e47-6cf0-4549-a2da-be7f6c04a808">
<img width="1860" alt="Capture d’écran 2024-02-18 à 17 42 00" src="https://github.com/EduWireApps/ecoledirecte-api-docs/assets/61110029/1852ee56-ce01-438a-b553-b99e55975a45">
<img width="1855" alt="Capture d’écran 2024-02-18 à 17 42 54" src="https://github.com/EduWireApps/ecoledirecte-api-docs/assets/61110029/df2a5927-b078-47c4-9b35-79c1143a2526">
<img width="1859" alt="Capture d’écran 2024-02-18 à 17 43 12" src="https://github.com/EduWireApps/ecoledirecte-api-docs/assets/61110029/b3172909-e5ae-4377-bc97-37773dd69788">

**Comment by LouisSimon2020** [comment]
Ok, j’ai finalement réussi à le faire fonctionner mais désormais, je n’ai pas trop compris comment supprimer, renommer, déplacer et ajouter des fichiers au cloud. Pourrais tu m’aider s’il te plaît. Merci beaucoup déjà pour ton aide concernant le téléchargement.

**Comment by MaitreRouge** [comment]
Hey, dans tes deux dernières captures d'écran tu as le contenu brut de tes fichiers, (le format étrange), t'as juste à les sauvegarder comme tels et boom t'as ton fichier. Pour le reste je te laisse chercher car c'est pas moi qui ait écrit la documentation sur le cloud ^^

**Comment by MaitreRouge** [comment]
Aucune activité depuis plus d'un mois, je ferme l'issue et te laisse en rouvrir une nouvelle en cas de besoin
