### ISSUE TITLE
Connexion impossible 

### ISSUE THREAD

**Issue by ABCraft19** [EduWireApps/ecoledirecte-api-docs#28]
Bonjour, suite à une supposé attaque DDOS d'école directe, ces derniers ont ajouté un système de QCM dans lequel on doit sélectionner notre prénom ce qui rend impossible l'utilisation de l'api

**Comment by azgaresncf** [comment]
Bonjour, j'ai fait une pull request concernant ce système de QCM. Elle arrive tout de suite (#27).

**Comment by azgaresncf** [comment]
Bonjour @ABCraft19. 
J'ai fait une pull request concernant ce système de QCM [ici](https://github.com/EduWireApps/ecoledirecte-api-docs/blob/21bfde7d66843a171fcb475e68efe4251eae3bcd/README.md#-concernant-la-connexion-qcm).

**Comment by ABCraft19** [comment]
Merci

**Comment by azgaresncf** [comment]
> Merci

Pas de souci, c'est normal ! 😉
