### ISSUE TITLE
c'est bien, mais ...

### ISSUE THREAD

**Issue by hp-fort** [EduWireApps/ecoledirecte-api-docs#3]
je n'arrive pas à envoyer de requetes pour récupérer mon token.
je ne sais pas ou chercher, avec postman, je ne sais pas ou mettre les arguments.
si tu peux m'aider je t'en serai très reconnaissant.

**Comment by MaitreRouge** [comment]
Il faut que tu renseignes tout dans postman comme décrit à cet endroit [https://github.com/EduWireApps/ecoledirecte-api-docs#login](https://github.com/EduWireApps/ecoledirecte-api-docs#login)
Si jamais tu as un problème avec postman je t'invite à directement aller sur leurs documentation/forums pour voir comment faire une requête POST comme détaillé [ici](https://fr.apis.support.brightcove.com/general/use-postman-api-requests.html#postRequest)

Pour rappel, ton body doit être envoyé comme raw et non pas comme json

**Comment by hp-fort** [comment]
bonjour, 
je pense avoir bien tout fait, comme indiquer dans la doc de postman ainsi que sur la vôtre de ED
![image](https://user-images.githubusercontent.com/96954861/194728669-a1f4bfa9-0aef-4518-903b-cbc811353f33.png)
Est-ce les bonne commande ? (c'est ma première api)

**Comment by Androz2091** [comment]
![Capture d’écran 2022-10-09 à 08 36 14](https://user-images.githubusercontent.com/42497995/194741828-b6e2f591-cc5d-491d-922e-47733963c070.png)
N'utilise pas le format JSON, c'est du form data. Si tu veux simplifier les choses, mets-le en "raw", avec `data=` devant le json

**Comment by hp-fort** [comment]
merci beaucoup,
 je regarde ça dès que je rentre chez moi

**Comment by KIZILANDO** [comment]
![image](https://user-images.githubusercontent.com/85397006/196005099-d74a1c8f-4794-4592-b17b-c01b8a16c463.png)
moi lorsque je veux avoir une timeline j'ai ca ou est mon erreur svp

**Comment by MaitreRouge** [comment]
Merci d'ouvrir une issue par sujet
