### ISSUE TITLE
Nouvelles infos pour la doc

### ISSUE THREAD

**Issue by ArtkiliouTheDev** [EduWireApps/ecoledirecte-api-docs#4]
MP moi pour beaucoup + d'infos détaillées sur la doc, j'en ai obtenu pas mal en 2 ans

**Comment by KIZILANDO** [comment]
> MP moi pour beaucoup + d'infos détaillées sur la doc, j'en ai obtenu pas mal en 2 ans

Bonjour, quel est ton discord ?

**Comment by ArtkiliouTheDev** [comment]
> > MP moi pour beaucoup + d'infos détaillées sur la doc, j'en ai obtenu pas mal en 2 ans
> 
> Bonjour, quel est ton discord ?

Monster Art#8392

**Comment by MaitreRouge** [comment]
Bonjour, peux tu directement mettre tes informations ici ?

**Comment by ArtkiliouTheDev** [comment]
{
    "accounts": [
        {
            "id": 1234, //int | Numéro de compte
            "main": true, // bool | Indique si cet account est principal
            "codeOgec": "0000000A", // str | Code RNE de l'établissement scolaire du compte
            "typeCompte": "P", // str | type du compte
            "identifiant": "Username", // str | Identifiant du compte
            "idLogin": 1234567, // int | Paramètre de cookie pour savoir si l'utilisateur est connecté via login/password
            "socketToken": "", // str | Websocket, à priori il n'est pas prit en compte concernant l'authentification (si on le change on ne sera pas déconnecté)
            "uid": "", // str | Il ne sert à rien lui aussi
            "modules": [],
            "profile": {}, // array | contient juste les informations personnelles du compte, pour l'affichage. Ne sert à rien dans l'authentification
            "parametresIndividuels": {
                "isQrcode": false, // bool | ???
                "lsuPoilDansLaMainBorne1": "", // int | Paramètre parcoursup
                "lsuPoilDansLaMainBorne2": "", // int | Paramètre parcoursup
                "lsuPoilDansLaMainBorne3": "", // int | Paramètre parcoursup
                "modeCalculLSU": "", // ??? | Paramètre de recommandation parcoursup
                "accessibilitéVisuelle": false, // bool | Pour les personnes malvoyantes, une police spéciale est mise en place
                "checkAuthentificationSecure": false, // bool | Mot secret au cas où l'utilisateur perds son mot de passe
                "checkFetS": true, // bool | ???
                "typeSaisieNotesDefaut": "", // str | ???
