### ISSUE TITLE
{"code":225,"data":null,"message":"Paramètres spécifiés incorrects !","host":"HTTP12"} lors du login

### ISSUE THREAD

**Issue by KIZILANDO** [EduWireApps/ecoledirecte-api-docs#40]
Lorsque je fais ma requete au doubleauth j'obtiens ceci mais je ne sais pas pourquoi.

**Comment by MrBeam89** [comment]
Bonsoir, pouvez vous nous montrer le contenu de votre requête pour regarder ce qui ne vas pas ? Bonne soirée.

**Comment by KIZILANDO** [comment]
Bon l'erreur a changé a present maintenant c'est : {'code': 522, 'token': '', 'message': 'Format JSON invalide.\nPour la chaîne du JEDObject', 'data': {'changementMDP': False, 'accounts': []}} pour le login. Voici mes headers : 
headers = {
    "authority": "api.ecoledirecte.com",
    "accept": "application/json, text/plain, */*",
    "content-type": "application/x-www-form-urlencoded",
    "origin": "https://www.ecoledirecte.com",
    "sec-ch-ua": '"Google Chrome";v="129", "Not=A?Brand";v="8", "Chromium";v="129"',
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": '"Windows"',
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-site",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
}
La requete : requests.post("https://api.ecoledirecte.com/v3/login.awp?v=4.63.0", data = {
    "data": {
        "identifiant": "identifiant",
        "motdepasse": "mdp",
        "isReLogin": False,
        "uuid": "",
        "fa": [
            {
                "cn": "lecn",
                "cv": "lecv"
            }
        ]
    }
}

**Comment by M6a5x98** [comment]
Peut-être que c’est `isRelogin` et pas `isReLogin` ?

**Comment by M6a5x98** [comment]
```python
identifiant = "identifiant"
passw = "motdepasse"
cn = "le_cn"
cv = "le_cv"
data='data={"identifiant": "'+identifiant+'","motdepasse": "'+passw+'","isRelogin": false,"uuid": "", "fa":[{"cn":"'+cn+'","cv":"'+cv+'"}]}'
# et après on fait la requête
```

**Comment by kekaaafm** [comment]
Aucune réponse depuis plus d'un mois, on considère l'issue comme résolue. Merci d'en ouvrir une nouvelle si le problème se représente
