### ISSUE TITLE
Erreur 522 ('Format JSON invalide. Pour la chaîne du JEDObject')

### ISSUE THREAD

**Issue by GGaby-LTG** [EduWireApps/ecoledirecte-api-docs#41]
```
``import` requests
import urllib
url = 'https://api.ecoledirecte.com/v3/login.awp'
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36',
          'Content-type': 'application/x-www-form-urlencoded',
          'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
          }
myobj = {
  "identifiant": "www",
  "motdepasse": "xxxx"
  "isRelogin": False,
  "uuid": ""
}
x = requests.post(url,headers=headers ,json = myobj)
**print(x.json())`**

```

          J'ai regardé l'autre thread avec l'erreur mais les changements au header le code ne marche toujours pas.

**Comment by kekaaafm** [comment]
Ton erreur est liée au fait que tu ne respecte pas le formatage des données qu'attends ED
Réfère toi à (l'issue 18) [](https://github.com/EduWireApps/ecoledirecte-api-docs/issues/18)

Pour rappel, il faut que tu envoies ton payload sous la frome d'un texte brut et non pas en JSON avec la structure suivante :
`
data={
"identifiant": "XXXx",
"motdepasse": "YYYY"
}
`

Si j'ai répondu a ton problème, merci de directement fermer l'issue. Dans le futur, vérifie en premier les issues qui ont déjà été fermés car elles peuvent déjà reprendre le problème que tu as eu
