### ISSUE TITLE
Télécharger un document depuis l'API ?

### ISSUE THREAD

**Issue by ArtOS-Developper** [EduWireApps/ecoledirecte-api-docs#6]
Bonjour,
Déjà merci pour cette doc. Elle est complète et simple à comprendre.

Mais je souhaiterais savoir comment télécharger un document. J'ai déjà trouvé l'URL :
`https://api.ecoledirecte.com/v3/telechargement.awp?verbe=get&fichierId=&leTypeDeFichier=Doc&archive=false&anneeArchive=&v=4.25.0`
Le truc, c'est que le fichier ne se télécharge pas. J'obtiens juste une chaine de caractères assez bizarre : 
`JVBERi0xLjcNCiW1tbW1DQoxIDAgb2JqDQo8PC9UeXBlL0NhdGFsb2cvUGFnZXMgMiAwIFIvTGFuZyhmci1GUikgL1N0cnVjdFRyZWVSb290IDQyIDAgUi9NYXJrSW5mbzw8L01hcmtlZCB0cnVlPj4vTWV0YWRhdGEgMjkxIDAgUi9WaWV3ZXJQcmVmZXJlbmNlcyAyOTIgMCBSPj4NCmVuZG9iag0KMiAwIG9iag0KPDwvVHlwZS9QYWdlcy9Db3VudCAxL0tpZHNbIDQgMCBSXSA+Pg0KZW5kb2JqDQozIDAgb2JqDQo8PC9BdXRob3IoU29waGllIFNQLiBQRVRSSSkgL0NyZWF0aW9uRGF0ZShEOjIwMjIxMjEyMDgzMTAxKzAxJz etc....` (elle n'est pas complète). 

On dirait du Base 64 et en effet, je trouve quelque chose en la décodant avec un site (https://www.base64decode.org/) :
`%PDF-1.7
%µµµµ
1 0 obj
<</Type/Catalog/Pages 2 0 R/Lang(fr-FR) /StructTreeRoot 42 0 R/MarkInfo<</Marked true>>/Metadata 291 0 R/ViewerPreferences 292 0 R>>
endobj
2 0 obj
<</Type/Pages/Count 1/Kids[ 4 0 R] >>
endobj
3 0 obj`

Mais le truc, c'est que le fichier n'est pas téléchargé.
Voici les headers de la requête / réponse (extrait avec les outils de dev de Firefox) : https://pastebin.com/NrTwsSTB

Mon but étant d'implémenter le téléchargement de documents (devoirs/doc eleves) depuis un client C# (Windows) et Swift (macOS). Mais quand je mets les données téléchargées dans un fichier, celui-ci n'est pas reconnu par Word ou Firefox (PDF) (Mon client EcoleDirecte : [AltDirecte](https://github.com/ArtOS-Developper/AltDirecte))

Je pensais alors ouvrir le navigateur pour faire télécharger le fichier, mais impossible de lui fournir le X-Token en headers, alors existe-t-il un autre moyen de lui passer le X-Token ou de faire télécharger le fichier ?

Exemple avec un fichier Word téléchargé depuis le cahier de texte
[exemple word.txt](https://github.com/EduWireApps/ecoledirecte-api-docs/files/10331361/exemple.word.txt)

**Comment by azgaresncf** [comment]
> Bonjour, Déjà merci pour cette doc. Elle est complète et simple à comprendre.
> 
> Mais je souhaiterais savoir comment télécharger un document. J'ai déjà trouvé l'URL : `https://api.ecoledirecte.com/v3/telechargement.awp?verbe=get&fichierId=&leTypeDeFichier=Doc&archive=false&anneeArchive=&v=4.25.0` Le truc, c'est que le fichier ne se télécharge pas. J'obtiens juste une chaine de caractères assez bizarre : `JVBERi0xLjcNCiW1tbW1DQoxIDAgb2JqDQo8PC9UeXBlL0NhdGFsb2cvUGFnZXMgMiAwIFIvTGFuZyhmci1GUikgL1N0cnVjdFRyZWVSb290IDQyIDAgUi9NYXJrSW5mbzw8L01hcmtlZCB0cnVlPj4vTWV0YWRhdGEgMjkxIDAgUi9WaWV3ZXJQcmVmZXJlbmNlcyAyOTIgMCBSPj4NCmVuZG9iag0KMiAwIG9iag0KPDwvVHlwZS9QYWdlcy9Db3VudCAxL0tpZHNbIDQgMCBSXSA+Pg0KZW5kb2JqDQozIDAgb2JqDQo8PC9BdXRob3IoU29waGllIFNQLiBQRVRSSSkgL0NyZWF0aW9uRGF0ZShEOjIwMjIxMjEyMDgzMTAxKzAxJz etc....` (elle n'est pas complète).
> 
> On dirait du Base 64 et en effet, je trouve quelque chose en la décodant avec un site (https://www.base64decode.org/) : `%PDF-1.7 %µµµµ 1 0 obj <</Type/Catalog/Pages 2 0 R/Lang(fr-FR) /StructTreeRoot 42 0 R/MarkInfo<</Marked true>>/Metadata 291 0 R/ViewerPreferences 292 0 R>> endobj 2 0 obj <</Type/Pages/Count 1/Kids[ 4 0 R] >> endobj 3 0 obj`
> 
> Mais le truc, c'est que le fichier n'est pas téléchargé. Voici les headers de la requête / réponse (extrait avec les outils de dev de Firefox) : https://pastebin.com/NrTwsSTB
> 
> Mon but étant d'implémenter le téléchargement de documents (devoirs/doc eleves) depuis un client C# (Windows) et Swift (macOS). Mais quand je mets les données téléchargées dans un fichier, celui-ci n'est pas reconnu par Word ou Firefox (PDF) (Mon client EcoleDirecte : [AltDirecte](https://github.com/ArtOS-Developper/AltDirecte))
> 
> Je pensais alors ouvrir le navigateur pour faire télécharger le fichier, mais impossible de lui fournir le X-Token en headers, alors existe-t-il un autre moyen de lui passer le X-Token ou de faire télécharger le fichier ?
> 
> Exemple avec un fichier Word téléchargé depuis le cahier de texte [exemple word.txt](https://github.com/EduWireApps/ecoledirecte-api-docs/files/10331361/exemple.word.txt)

Oui, Firefox encrypte automatiquement en Base64 les réponses faites à des API (je ne comprends pas même l'intérêt qu'il fasse ça au passage 🤷🏻‍♂️).

Pour expliquer, la requête ``https://api.ecoledirecte.com/v3/telechargement.awp`` est faite en POST, et n'est initialement faite pour télécharger des documents, mais pour les AFFICHER depuis ED.

Comme marqué dans la documentation depuis :
**La réponse est le contenu du document**.

Il suffit alors de transposer la réponse complète de la requête directement sur un fichier en ``.pdf``.

**Comment by RetroAndDev** [comment]
👌 Parfait. J'essayerais quand je ferais la v2 de mon App
Question sais tu comment marche aussi le téléchargement depuis les espaces de travail ?

**Comment by azgaresncf** [comment]
> 👌 Parfait. J'essayerais quand je ferais la v2 de mon App Question sais tu comment marche aussi le téléchargement depuis les espaces de travail ?

Tout dépend de si le document que tu souhaites télécharger est publiée sur ED ou sur un site externe.
Si il est interne (publié sur ED), il suffit de faire une requête basique à ``https://api.ecoledirecte.com/v3/telechargement.awp?verbe=get&fichierId=(chemin vers le fichier en question)&leTypeDeFichier=CLOUD&idEntity=(ID de l'espace de travail)&typeEntity=W``.

Je vais essayer de me renseigner vite fait concernant les documents externes.

**Comment by azgaresncf** [comment]
> 👌 Parfait. J'essayerais quand je ferais la v2 de mon App Question sais tu comment marche aussi le téléchargement depuis les espaces de travail ?

N'hésite pas à m'envoyer un message sur Discord, j'essayerais de t'aider à intégrer l'API si jamais tu as besoin.

**Comment by RetroAndDev** [comment]
Okay je ferais un test "demain" avec Postman.
En parlant de doc externe, quand on ouvre un manuel cela fait une redirection via api.ecoledirecte.com mais je n'arrive pas à lui fournir le Token saurais tu comment lui fournir ? (J'ai essayé via l'URL, les header mais il dit toujours que le token a expiré alors que non)

**Comment by azgaresncf** [comment]
> Okay je ferais un test "demain" avec Postman. En parlant de doc externe, quand on ouvre un manuel cela fait une redirection via api.ecoledirecte.com mais je n'arrive pas à lui fournir le Token saurais tu comment lui fournir ? (J'ai essayé via l'URL, les header mais il dit toujours que le token a expiré alors que non)

Un manuel ?
Si tu parles de manuel scolaire, je n'ai malheureusement accès à aucun d'entre eux.

**Comment by RetroAndDev** [comment]
> > 👌 Parfait. J'essayerais quand je ferais la v2 de mon App Question sais tu comment marche aussi le téléchargement depuis les espaces de travail ?
> 
> 
> 
> N'hésite pas à m'envoyer un message sur Discord, j'essayerais de t'aider à intégrer l'API si jamais tu as besoin.

Okay je fait cela

**Comment by RetroAndDev** [comment]
> > Okay je ferais un test "demain" avec Postman. En parlant de doc externe, quand on ouvre un manuel cela fait une redirection via api.ecoledirecte.com mais je n'arrive pas à lui fournir le Token saurais tu comment lui fournir ? (J'ai essayé via l'URL, les header mais il dit toujours que le token a expiré alors que non)
> 
> 
> 
> Un manuel ?
> 
> Si tu parles de manuel scolaire, je n'ai malheureusement accès à aucun d'entre eux.

Ah okay, peut être via les cookies. J'essayerais

**Comment by azgaresncf** [comment]
> > Okay je ferais un test "demain" avec Postman. En parlant de doc externe, quand on ouvre un manuel cela fait une redirection via api.ecoledirecte.com mais je n'arrive pas à lui fournir le Token saurais tu comment lui fournir ? (J'ai essayé via l'URL, les header mais il dit toujours que le token a expiré alors que non)
> 
> Un manuel ? Si tu parles de manuel scolaire, je n'ai malheureusement accès à aucun d'entre eux.

Néanmoins, je peux essayer de voir son fonctionnement avec les fichiers javascript d'ED, mais ça risque de prendre juste un peu plus de temps.

Aurais-tu des endpoints que ED utilise pour ouvrir ces dits-manuels afin d'affiner mes recherches ?

**Comment by RetroAndDev** [comment]
Oui je peux te les donner "demain" enfin tout à l'heure.
J'ai pas accès à mon mac pour le momen

**Comment by azgaresncf** [comment]
> Oui je peux te les donner "demain" enfin tout à l'heure. J'ai pas accès à mon mac pour le momen

Aucun souci 👌🏻

**Comment by azgaresncf** [comment]
![image](https://github.com/EduWireApps/ecoledirecte-api-docs/assets/50982832/02df81a0-9a42-481a-a09a-b7cbb1bc2902)
Ma piste de recherche va commencer à partir de cet endpoint

**Comment by RetroAndDev** [comment]
Oui, cela donne une Array des manuels. Mais après c'est pour l'ouvrir le problème.

**Comment by azgaresncf** [comment]
Qu'affiche-t-il comme d'exemple d'``urlTelechargement`` ?

**Comment by RetroAndDev** [comment]
> Qu'affiche-t-il comme d'exemple d'``urlTelechargement`` ?

Bonne question, je crois que c'est l'URL qui redirige vers le service du manuel.

**Comment by azgaresncf** [comment]
> > Qu'affiche-t-il comme d'exemple d'`urlTelechargement` ?
> 
> Bonne question, je crois que c'est l'URL qui redirige vers le service du manuel.

Tout dépend de quel service il s'agit (LeLivreScolaire ? Un CAS externe ?)

**Comment by azgaresncf** [comment]
(PS: si tu ne souhaites communiquer certaines données, je t'invite plutôt de le faire à partir de discord (@azgaresncf))

**Comment by RetroAndDev** [comment]
> > > Qu'affiche-t-il comme d'exemple d'`urlTelechargement` ?
> 
> > 
> 
> > Bonne question, je crois que c'est l'URL qui redirige vers le service du manuel.
> 
> 
> 
> Tout dépend de quel service il s'agit (LeLivreScolaire ? Un CAS externe ?)

Oui c'est cela. Si le manuel est sur BiblioManuels ou Educadhoc par exemple cela va rediriger sur le site du service pour consulter ou télécharger le manuel

**Comment by azgaresncf** [comment]
> > > > Qu'affiche-t-il comme d'exemple d'`urlTelechargement` ?
> > 
> > 
> > > 
> > 
> > 
> > > Bonne question, je crois que c'est l'URL qui redirige vers le service du manuel.
> > 
> > 
> > Tout dépend de quel service il s'agit (LeLivreScolaire ? Un CAS externe ?)
> 
> Oui c'est cela. Si le manuel est sur BiblioManuels ou Educadhoc par exemple cela va rediriger sur le site du service pour consulter ou télécharger le manuel

Quel enfer :')

**Comment by RetroAndDev** [comment]
> (PS: si tu ne souhaites communiquer certaines données, je t'invite plutôt de le faire à partir de discord (@azgaresncf))

Okay, de toute façon je vais allez me coucher je pourrais continuer a voir demain et à aider pour la doc
(D'ailleurs la doc est bien mieux j'avais pas vu les dernières modifications bravo à vous)

**Comment by azgaresncf** [comment]
> > (PS: si tu ne souhaites communiquer certaines données, je t'invite plutôt de le faire à partir de discord (@azgaresncf))
> 
> Okay, de toute façon je vais allez me coucher je pourrais continuer a voir demain et à aider pour la doc (D'ailleurs la doc est bien mieux j'avais pas vu les dernières modifications bravo à vous)

Aucun souci 👌🏻
Bonne nuit à toi !

**Comment by RetroAndDev** [comment]
> > > > > Qu'affiche-t-il comme d'exemple d'`urlTelechargement` ?
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Bonne question, je crois que c'est l'URL qui redirige vers le service du manuel.
> 
> > > 
> 
> > > 
> 
> > > Tout dépend de quel service il s'agit (LeLivreScolaire ? Un CAS externe ?)
> 
> > 
> 
> > Oui c'est cela. Si le manuel est sur BiblioManuels ou Educadhoc par exemple cela va rediriger sur le site du service pour consulter ou télécharger le manuel
> 
> 
> 
> Quel enfer :')

Oui l'api de ED est vraiment mal foutue. Je me demande comment ils font...

**Comment by azgaresncf** [comment]
> > > > > > Qu'affiche-t-il comme d'exemple d'`urlTelechargement` ?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > Bonne question, je crois que c'est l'URL qui redirige vers le service du manuel.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Tout dépend de quel service il s'agit (LeLivreScolaire ? Un CAS externe ?)
> > 
> > 
> > > 
> > 
> > 
> > > Oui c'est cela. Si le manuel est sur BiblioManuels ou Educadhoc par exemple cela va rediriger sur le site du service pour consulter ou télécharger le manuel
> > 
> > 
> > Quel enfer :')
> 
> Oui l'api de ED est vraiment mal foutue. Je me demande comment ils font...

Mieux vaut ça que PRONOTE... (je te laisse aller [lire le protocole de leur API (en Anglais)](https://github.com/bain3/pronotepy/blob/master/PRONOTE%20protocol.md), où Index-Education essaye de faire en sorte que l'API soit tout simplement incompréhensible par les utilisateurs pour notamment éviter une utilisation tierce de leurs services (=autre que par leur site).

**Comment by azgaresncf** [comment]
> > > > > > > Qu'affiche-t-il comme d'exemple d'`urlTelechargement` ?
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > > Bonne question, je crois que c'est l'URL qui redirige vers le service du manuel.
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > Tout dépend de quel service il s'agit (LeLivreScolaire ? Un CAS externe ?)
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Oui c'est cela. Si le manuel est sur BiblioManuels ou Educadhoc par exemple cela va rediriger sur le site du service pour consulter ou télécharger le manuel
> > > 
> > > 
> > > Quel enfer :')
> > 
> > 
> > Oui l'api de ED est vraiment mal foutue. Je me demande comment ils font...
> 
> Mieux vaut ça que PRONOTE... (je te laisse aller [lire le protocole de leur API (en Anglais)](https://github.com/bain3/pronotepy/blob/master/PRONOTE%20protocol.md), où Index-Education essaye de faire en sorte que l'API soit tout simplement incompréhensible par les utilisateurs pour notamment éviter une utilisation tierce de leurs services (=autre que par leur site).
> 
> Pour te faire simple, c'est un mélange de web-scraping et de requêtes "chiffrées" et trackées à la moindre action. Si tu fais un oubli même d'une simple requête, tu te fais automatiquement rejeter par l'API.

Au passage, IE fait automatiquement pression sur certains projets (plus d'actualité normalement), dont je ne comprends pas la motivation (les raisons de pourquoi ils souhaitent mettre la pression sur ces projets parait juste vague et totalement dénuée de sens).

EcoleDirecte quant à lui, ne dispose d'aucune interdiction précisée concernant l'utilisation tierce de leur API, même si il fait gaffe au moindre formatage de requête par exemple.
