### ISSUE TITLE
Contribution à la documentation

### ISSUE THREAD

**Issue by Chromosore** [EduWireApps/ecoledirecte-api-docs#8]
Salut, j'ai moi aussi "cartographié" l'API écoledirecte ces derniers jours et j'ai construit un fichier avec une liste assez exhaustive des routes élèves de l'API. C'est seulement après que je me suis dis qu'il devait déjà avoir des projets de documentation 🤦

Bref je pense que ce serait bien que j'intègre mes trouvailles dans cette doc, ne serait-ce que pour la visibilité, plutôt que de créer mon propre projet.

**Comment by MaitreRouge** [comment]
Ca serait génial !

Hésite pas à envoyer ton fichier ou a faire un PR !

**Comment by azgaresncf** [comment]
> Salut, j'ai moi aussi "cartographié" l'API écoledirecte ces derniers jours et j'ai construit un fichier avec une liste assez exhaustive des routes élèves de l'API. C'est seulement après que je me suis dis qu'il devait déjà avoir des projets de documentation 🤦
> 
> Bref je pense que ce serait bien que j'intègre mes trouvailles dans cette doc, ne serait-ce que pour la visibilité, plutôt que de créer mon propre projet.

Bien le bonjour !
Je compte moi aussi aider sur la documentation de certains endpoints Elèves (commandes). Je travaille déjà dessus.
![image](https://github.com/EduWireApps/ecoledirecte-api-docs/assets/50982832/608596f7-f696-4de5-86d0-c24391bb2dfe)
